/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/header/AppHeader.vue')['default']
    AppHeaderLinks: typeof import('./components/header/AppHeaderLinks.vue')['default']
    CategoryModal: typeof import('./components/shared/CategoryModal.vue')['default']
    Check: typeof import('./components/icons/Check.vue')['default']
    HeroSection: typeof import('./components/home/HeroSection.vue')['default']
    HiredMeModal: typeof import('./components/shared/HiredMeModal.vue')['default']
    HireMeModal: typeof import('./components/shared/HireMeModal.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ProjectGrid: typeof import('./components/project/ProjectGrid.vue')['default']
    ProjectHeader: typeof import('./components/project/ProjectHeader.vue')['default']
    ProjectInfo: typeof import('./components/project/ProjectInfo.vue')['default']
    ProjectsFilter: typeof import('./components/project/ProjectsFilter.vue')['default']
    ProjectsGrid: typeof import('./components/project/ProjectsGrid.vue')['default']
    ProjectSingle: typeof import('./components/project/ProjectSingle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
